# Basic
title: 大黄的技术博客
subtitle: 编程与游戏
welcome_message: 如果有的选，那就选做自己喜欢的事情。
description: 黄恩岩，港漂，程序员，桌游爱好者
creator: <a href="https://github.com/huangenyan">黄恩岩</a>

url: "https://huangenyan.github.io"

permalink: /:year/:month/:title/

# Format
markdown: kramdown
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 查看所有文章

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 查看我的开源项目, url: 'https://github.com/huangenyan?tab=repositories'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: huangenyan
    # duoshuo:

# Social
social:
    weibo: 1673965165
    github: huangenyan
    twitter: huangenyan
    gplus: 106794116801750969302
    mail: huangenyan@gmail.com

# Google Analytics
ga:
    id: UA-77867720-1
    host: huangenyan.github.io
