name: 大黄的技术博客
description: 编程与游戏
meta_description: "Enyan Huang's blog"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'https://huangenyan.github.io'
google_analytics: 'UA-77867720-1'
disqus: true
disqus_shortname: 'huangenyan'

# Details for the RSS feed generator
url:            'https://huangenyan.github.io/subscribe'
author:         'Enyan Huang'
authorTwitter:  'huangenyan'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
